# Generated by Django 4.2.6 on 2023-10-18 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99, verbose_name='Titolo')),
                ('city', models.CharField(max_length=99, verbose_name='Città')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('thumbnail', models.ImageField(blank=True, default=False, null=True, upload_to='', verbose_name='Immagine di copertina')),
                ('gallery', models.ImageField(upload_to='', verbose_name='Galleria Immagini')),
                ('virtual_tour', models.CharField(help_text='Inserire il link Matterport', max_length=99, verbose_name='Link Virtual Tour')),
            ],
            options={
                'verbose_name': 'Immobile',
                'verbose_name_plural': 'Immobili',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(default='Galleria Immagini')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.property')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
