# Generated by Django 4.2.6 on 2023-10-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Foto', 'verbose_name_plural': 'Foto'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='gallery',
        ),
        migrations.AlterField(
            model_name='property',
            name='thumbnail',
            field=models.ImageField(upload_to='', verbose_name='Immagine di copertina'),
        ),
    ]
