# Generated by Django 4.2.6 on 2023-10-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_photo_options_remove_property_gallery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='title',
            new_name='property',
        ),
    ]
