# Generated by Django 4.2.6 on 2023-10-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_title_photo_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='property',
            new_name='city',
        ),
    ]
